# project_config.yaml

model_config:
  validation_metric: MAPE
  optimization_metric: MSE
  model_name: Stock_Predictor
  test_size: 0.2
  TARGET_NAME: Close
  forecast_horizon: 7

data_config:
  period: 3600d
  interval: 1d
  ticker_symbol: BOVA11.SA
  tickers_list: 
    - BOVA11.SA
    - BCFF11.SA
    - TAEE4.SA
    - EGIE3.SA
    - BBSE3.SA
    - CSMG3.SA
    - PETR4.SA
    - BRSR6.SA

features_list:
  - day_of_month
  - month
  - day_of_week
  - week_of_month
  - quarter
  - CLOSE_MA_3
  - Close_lag_1
  - Close_lag_2

paths:
  root_data_path: ./data
  raw_data_path: data/raw
  processed_data_path: data/processed
  output_data_path: data/output
  models_path: ./models
